#!/bin/bash
do_help=no
img=yes
snd=yes
webpage=""


while [ -n "$1" ]; do
        case "$1" in
                --help)
                        do_help=yes
                        break
                        ;;
                -i)
                        shift
                        snd=no

                        ;;
                -s)
                        shift
                        img=no

                        ;;
                 *.html) webpage="$1"
                        ;;
                *) do_help = yes
                   break
                   ;;
        esac
        shift
done

if [[ "$do_help" = yes ]]; then
                        echo "-i for images only"
                        echo "-s for sounds only"
                        echo "--help for help"
                        echo "just webpege for both sounds and images"
fi

if [[ -n "$webpage" ]]; then
                        if [[ "$img" = yes ]]; then
                                                cat "$webpage" | grep -w "[^ ]*.jpg\>"
                                                cat "$webpage" | grep -w "[^ ]*.png\>"
                                                cat "$webpage" | grep -w "[^ ]*.svg\>"
                        fi

                        if [[ "$snd" = yes ]]; then
                                                cat "$webpage" | grep -w "[^ ]*.waw\>"
                                                cat "$webpage" | grep -w "[^ ]*.mp3\>"
                                                cat "$webpage" | grep -w "[^ ]*.ogg\>"
                        fi
fi
